### ISSUE TITLE
ImportError: please install dataloader

### ISSUE THREAD

**Issue by HuntZhaozq** [bytedance/Shot2Story#2]
When I run demo_video.py. The error occurs: ImportError: please install dataloader.
Whether it lacks of the file of dataloader.py?
Could you please upload it ?

**Comment by youthHan** [comment]
Hi @HuntZhaozq 

Please provide a full log so I can help you get through this. A hint: make sure you run the demo under `code` directory.

**Comment by Minniemu** [comment]
Hi @youthHan:

I also encounter the same problem. Can you help me figure out the problem? 
Here is my error message:
```
Traceback (most recent call last):
  File "/eva_data1/minnie/dataset/Shot2Story/code/lavis/datasets/datasets/hdfs_video_caption_datasets.py", line 16, in <module>
    from dataloader import KVReader
ModuleNotFoundError: No module named 'dataloader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/demo_video.py", line 9, in <module>
    import lavis.tasks as tasks
  File "/eva_data1/minnie/dataset/Shot2Story/code/lavis/__init__.py", line 15, in <module>
    from lavis.datasets.builders import *
  File "/eva_data1/minnie/dataset/Shot2Story/code/lavis/datasets/builders/__init__.py", line 9, in <module>
    from lavis.datasets.builders.caption_builder import (
  File "/eva_data1/minnie/dataset/Shot2Story/code/lavis/datasets/builders/caption_builder.py", line 27, in <module>
    from lavis.datasets.datasets.hdfs_video_caption_datasets import (
  File "/eva_data1/minnie/dataset/Shot2Story/code/lavis/datasets/datasets/hdfs_video_caption_datasets.py", line 18, in <module>
    raise ImportError("Please install dataloader")
ImportError: Please install dataloader
```

**Comment by youthHan** [comment]
@Minniemu This package is unrelated to the method and will not be used. I created a [quick branch](https://github.com/bytedance/Shot2Story/tree/temp) and removed all the related lines. 
As the machines are highly demanded currently, I cannot make a test soon. Please give a try of the branch and feel free to raise questions.

**Comment by Minniemu** [comment]
@youthHan Thanks for your help~! There is no ImportError now, but there is a problem while I use the provided `.yaml` file to build the Conda environment, which lots of packages will encounter conflict between them.

**Comment by youthHan** [comment]
I see. Can the demo run now? The env is same to one on my side.

**Comment by youthHan** [comment]
Hi! Due to inactivity, I may close this issue. Feel free to open a new one or reopen if new problems arise.
